### ISSUE TITLE
Cannot download the ROS bag 

### ISSUE THREAD

**Issue by StevenS963** [zhanghanduo/ROS_leaflet_gps#1]
Hi there, I do really interest in the program. However, when I try to download the ROS bag, the website told me "This link has been removed". Does anyone has any idea about that? Or do you have any other way to get the ROS bag again? Thanks

**Comment by zhanghanduo** [comment]
Sorry I deleted the ros bag accidentally. I forgot that link belongs to this repo :( 
Actually you don't need a demo rosbag. As long as your ros topics contain robot pose msgand gps msg (geometry_msgs/PoseWithCovarianceStamped), you can just use `scripts_resuse_path.js`. Just remember to check whether your robot pose coordinate is z_up,x_forward or z_forward, x_right. If z_up, set it to true. 
My documentation was not managed well. When I am free, I will try to complete the docs.
